In [3]:
import numpy as np
seq = [1,2,3,4,5]
arr = np.array(seq)
arr

array([1, 2, 3, 4, 5])

In [12]:
arr1 = np.zeros(10)
arr1

arr2 = np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr3 = np.ones((2,3,4))
arr3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
arr4 = np.empty((2,3,4))
arr4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
ones = np.eye(4)
ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
ran = np.arange(1,20)
ran

ran.ndim
print(ran.shape)
print(arr4.shape)


(19,)
(2, 3, 4)


In [35]:
# explicit typecasting

np.array1 = arr4.astype(np.float64)
print(np.array1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
